# Generated by Django 3.1.7 on 2022-11-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20221109_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Reference',
            field=models.TextField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='codigo_ean',
            field=models.TextField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(max_length=32),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(upload_to='store/products'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='rating',
            field=models.FloatField(max_length=32),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='review',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='subject',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='variationproduct',
            name='variation_value',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='variationproductcolor',
            name='variation_value',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='variationproductplus',
            name='variation_value',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='variationproductsize',
            name='variation_value',
            field=models.CharField(max_length=128),
        ),
    ]
