# Generated by Django 3.1 on 2022-11-09 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20221109_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variationproduct',
            name='variation_value',
        ),
    ]
